/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.call_of_rum.boundary.presentation;

import fr.call_of_rum.boundary.dialog.IDialog;
import fr.call_of_rum.util.CellType;

/**
 *
 * @author Solène
 */
public class BoardPanel extends javax.swing.JPanel {

    private IDialog iDialog;
    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        iDialog=new IDialog(){
            @Override
            public CellType askCellType(int index){
                return CellType.NORMAL;
            }
        };
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cellPanel1 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel1.setNum(1);
        cellPanel1.setType(iDialog.askCellType(1));
        cellPanel2 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel2.setNum(2);
        cellPanel2.setType(iDialog.askCellType(2));
        cellPanel3 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel3.setNum(3);
        cellPanel3.setType(iDialog.askCellType(3));
        cellPanel4 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel4.setNum(4);
        cellPanel4.setType(iDialog.askCellType(4));
        cellPanel5 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel5.setNum(5);
        cellPanel5.setType(iDialog.askCellType(5));
        cellPanel6 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel6.setNum(6);
        cellPanel6.setType(iDialog.askCellType(6));
        cellPanel30 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel30.setNum(30);
        cellPanel30.setType(iDialog.askCellType(30));
        cellPanel23 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel23.setNum(23);
        cellPanel23.setType(iDialog.askCellType(23));
        cellPanel22 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel22.setNum(22);
        cellPanel22.setType(iDialog.askCellType(22));
        cellPanel15 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel15.setNum(15);
        cellPanel15.setType(iDialog.askCellType(15));
        cellPanel14 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel14.setNum(14);
        cellPanel14.setType(iDialog.askCellType(14));
        cellPanel7 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel7.setNum(7);
        cellPanel7.setType(iDialog.askCellType(7));
        cellPanel24 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel24.setNum(24);
        cellPanel24.setType(iDialog.askCellType(24));
        cellPanel21 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel21.setNum(21);
        cellPanel21.setType(iDialog.askCellType(21));
        cellPanel16 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel16.setNum(16);
        cellPanel16.setType(iDialog.askCellType(16));
        cellPanel13 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel13.setNum(13);
        cellPanel13.setType(iDialog.askCellType(13));
        cellPanel8 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel8.setNum(8);
        cellPanel8.setType(iDialog.askCellType(8));
        cellPanel29 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel29.setNum(29);
        cellPanel29.setType(iDialog.askCellType(29));
        cellPanel28 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel28.setNum(28);
        cellPanel28.setType(iDialog.askCellType(28));
        cellPanel25 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel25.setNum(25);
        cellPanel25.setType(iDialog.askCellType(25));
        cellPanel20 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel20.setNum(20);
        cellPanel20.setType(iDialog.askCellType(20));
        cellPanel17 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel17.setNum(17);
        cellPanel17.setType(iDialog.askCellType(17));
        cellPanel12 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel12.setNum(12);
        cellPanel12.setType(iDialog.askCellType(12));
        cellPanel9 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel9.setNum(9);
        cellPanel9.setType(iDialog.askCellType(9));
        cellPanel27 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel27.setNum(27);
        cellPanel27.setType(iDialog.askCellType(27));
        cellPanel26 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel26.setNum(26);
        cellPanel26.setType(iDialog.askCellType(26));
        cellPanel19 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel19.setNum(19);
        cellPanel19.setType(iDialog.askCellType(19));
        cellPanel18 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel18.setNum(18);
        cellPanel18.setType(iDialog.askCellType(18));
        cellPanel11 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel11.setNum(11);
        cellPanel11.setType(iDialog.askCellType(11));
        cellPanel10 = new fr.call_of_rum.boundary.presentation.CellPanel();
        cellPanel10.setNum(10);
        cellPanel10.setType(iDialog.askCellType(10));

        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cellPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cellPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cellPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cellPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cellPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cellPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cellPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cellPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cellPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cellPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cellPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cellPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cellPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cellPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cellPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cellPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cellPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cellPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cellPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cellPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cellPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellPanel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel1;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel10;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel11;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel12;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel13;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel14;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel15;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel16;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel17;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel18;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel19;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel2;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel20;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel21;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel22;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel23;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel24;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel25;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel26;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel27;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel28;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel29;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel3;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel30;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel4;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel5;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel6;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel7;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel8;
    private fr.call_of_rum.boundary.presentation.CellPanel cellPanel9;
    // End of variables declaration//GEN-END:variables
}
