/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.call_of_rum.boundary.presentation;

import fr.call_of_rum.boundary.dialog.DialogStub;
import fr.call_of_rum.boundary.dialog.IDialog;

import javax.swing.*;
import java.util.Random;

/**
 *
 * @author assanendoye
 */
public class DicePanel extends javax.swing.JPanel {

    /**
     * Creates new form DicePanel
     */

    private int valueFace1;
    private int valueFace2;

    private int tour;
    private IDialog dialog;

    public void setDialog(IDialog dialog) {
        this.dialog = dialog;
    }

    public DicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dice1 = new fr.call_of_rum.boundary.presentation.Dice();
        dice2 = new fr.call_of_rum.boundary.presentation.Dice();
        throwDiceButton = new javax.swing.JButton();

        javax.swing.GroupLayout dice1Layout = new javax.swing.GroupLayout(dice1);
        dice1.setLayout(dice1Layout);
        dice1Layout.setHorizontalGroup(
            dice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        dice1Layout.setVerticalGroup(
            dice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dice2Layout = new javax.swing.GroupLayout(dice2);
        dice2.setLayout(dice2Layout);
        dice2Layout.setHorizontalGroup(
            dice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        dice2Layout.setVerticalGroup(
            dice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        throwDiceButton.setText("Lancer dés");
        throwDiceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                throwDiceButton1MouseClicked();
            }
        });
        throwDiceButton.addActionListener(this::throwDiceButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(throwDiceButton)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(throwDiceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void throwDiceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throwDiceButton1ActionPerformed
    }//GEN-LAST:event_throwDiceButton1ActionPerformed

    private void throwDiceButton1MouseClicked() {//GEN-FIRST:event_throwDiceButton1MouseClicked
        if (throwDiceButton.isEnabled()) {
            throwDice();
        }
    }//GEN-LAST:event_throwDiceButton1MouseClicked
    public static int generateRandomNumber() {
        Random rand = new Random();
        return rand.nextInt(6) + 1; // Génère un nombre entre 0 et 5, on ajoute 1 pour obtenir un nombre entre 1 et 6
    }
    public static void wait(int milliseconds) {
        try {
            Thread.sleep(milliseconds);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
    
    private static final Random RNG = new Random();
    
    public void throwDice(){
        throwDiceButton.setEnabled(false);
        dialog.trowDice();
        int value = dialog.getDicesResult();

        int maxFirst = value > 6 ? 7 : value;
        do {
            valueFace1 = RNG.nextInt(1, maxFirst + 1); // result of the first dice
            valueFace2 = value - valueFace1; // result of the second dice
        } while (valueFace2 == 0);
        System.out.println("dice 1 :" +valueFace1+"dice 1 :"+valueFace2);
        timer.start();
    }
    private

    Timer timer = new Timer(100, (e) -> {
        setRandomFace();
    });

    private void setRandomFace() {
        timer.stop();
        tour++;
        if (tour < 6) {
            dice1.setFaceValue(generateRandomNumber());
            dice2.setFaceValue(generateRandomNumber());
            timer.start();
        } else {
            dice1.setFaceValue(valueFace1);
            dice2.setFaceValue(valueFace2);
            tour = 0;
            throwDiceButton.setEnabled(true);
        }
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("Dice Faces");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 400); // Taille de la fenêtre
        DicePanel dicePanel = new DicePanel();
        frame.add(dicePanel);
        dicePanel.setDialog(new DialogStub());
        frame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.call_of_rum.boundary.presentation.Dice dice1;
    private fr.call_of_rum.boundary.presentation.Dice dice2;
    private javax.swing.JButton throwDiceButton;

    // End of variables declaration//GEN-END:variables
}
