/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.call_of_rum.boundary.presentation;

import fr.call_of_rum.boundary.dialog.IDialog;
import fr.call_of_rum.util.ItemType;

import java.awt.*;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author wil-mcjohnley
 */
public class GraphicsCard extends javax.swing.JPanel {
    private ItemType imageName;
    private  IDialog dialog;
    private boolean clickable = true;



    public GraphicsCard() {
        initComponents();
    }
    
    public void setImage(ItemType item){
        this.imageName=item;
        designImage(dialog.getPrice(item),dialog.getNameItem(item),dialog.getDescribe(item));
    }
    
    public void setDialog(IDialog dialog){
        this.dialog = dialog;
    }

    public ItemType getItemType() {
        return imageName;
    }

    private void designImage(int value, String nameValue, String descriptionValue){
        BufferedImage image = ImageLoader.loadImage("presentation/"+imageName.toString().toLowerCase()+".png");
        Image scaledTypeImage;
        scaledTypeImage = image.getScaledInstance(imageContainer.getWidth(), imageContainer.getHeight(), Image.SCALE_SMOOTH);
        imageContainer.setLocation(0, getWidth()/2);
        price.setText(""+value);
        nameLabel.setText(nameValue);
        description.setText(descriptionValue);
        
        ImageIcon typeIcon = new ImageIcon(scaledTypeImage);
        imageContainer.setIcon(typeIcon);
    }

    // Méthode pour mettre à jour l'état de clic
    private void updateClickableState() {
        setEnabled(false); // Désactive le clic si le JPanel n'est pas cliquable
        if (!clickable) {
            setForeground(Color.PINK); // Grise visuellement le JPanel
        }
    }

    // Méthode pour activer ou désactiver le clic
    public void setClickable(boolean clickable) {
        this.clickable = clickable;
        System.out.println("je ne suis pâs sensé etre clicable");
        updateClickableState(); // Met à jour l'état de clic après chaque modification
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageContainer = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        description = new javax.swing.JLabel();

        nameLabel.setText("0");

        price.setText("jLabel1");

        description.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(description)
                    .addComponent(price))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel)
                .addGap(10, 10, 10)
                .addComponent(price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JLabel imageContainer;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
