/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fr.call_of_rum.boundary.presentation;


import fr.call_of_rum.util.CellType;
import fr.call_of_rum.util.ItemType;
import fr.call_of_rum.util.Player;
import fr.call_of_rum.boundary.dialog.IDialog;

import java.awt.*;
import javax.swing.*;

import java.awt.event.MouseEvent;
import java.util.*;
import java.util.List;

import static fr.call_of_rum.util.ItemType.*;

/**
 *
 * @author assanendoye
 */
public class Market extends javax.swing.JDialog {

    /**
     * Creates new form Market
     */
    public Market(Frame parent,boolean modal ,Player player, IDialog dialog) {
        super(parent,modal);
        this.player = player;
        this.dialog = dialog;
        focus = new HashMap<>();
        this.size = dialog.getSizeInventaireAvailable(player);
        itemTypesSelect = new ArrayList<>();
        score = dialog.checkfound(player);
        itemTypes = dialog.getItemMarket();

        initComponents();

        focus.put(graphicsCard1, false);
        focus.put(graphicsCard2, false);
        focus.put(graphicsCard3, false);
        focus.put(graphicsCard4, false);
        
        graphicsCard4.setDialog(dialog);
        graphicsCard3.setDialog(dialog);
        graphicsCard2.setDialog(dialog);
        graphicsCard1.setDialog(dialog);
        
        graphicsCard1.setImage(itemTypes[0]);
        graphicsCard2.setImage(itemTypes[1]);
        graphicsCard3.setImage(itemTypes[2]);
        graphicsCard4.setImage(itemTypes[3]);

        inventoryPanel1.setDialog(dialog);
        updateMarket();
        inventoryPanel1.setInventory(RUM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coinScorePanel1 = new fr.call_of_rum.boundary.presentation.CoinScorePanel();
        graphicsCard2 = new fr.call_of_rum.boundary.presentation.GraphicsCard();
        graphicsCard3 = new fr.call_of_rum.boundary.presentation.GraphicsCard();
        graphicsCard4 = new fr.call_of_rum.boundary.presentation.GraphicsCard();
        graphicsCard1 = new fr.call_of_rum.boundary.presentation.GraphicsCard();
        inventoryPanel1 = new fr.call_of_rum.boundary.presentation.InventoryPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Valider");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/market.png"))); // NOI18N

        jLabel2.setText("Market");

        jLabel3.setText("Bienvenue dans le marché");

        graphicsCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        graphicsCard2.setEnabled(false);
        graphicsCard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphicsCard2MouseClicked(evt);
            }
        });

        graphicsCard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        graphicsCard3.setMinimumSize(new java.awt.Dimension(400, 400));
        graphicsCard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphicsCard3MouseClicked(evt);
            }
        });

        graphicsCard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        graphicsCard4.setPreferredSize(new java.awt.Dimension(400, 400));
        graphicsCard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphicsCard4MouseClicked(evt);
            }
        });

        graphicsCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        graphicsCard1.setEnabled(false);
        graphicsCard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphicsCard1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coinScorePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(graphicsCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(graphicsCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(graphicsCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(graphicsCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coinScorePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inventoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphicsCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(graphicsCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphicsCard3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graphicsCard4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        valider();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        valider();
    }//GEN-LAST:event_jButton1MouseClicked


    private void graphicsCard3MouseClicked(MouseEvent evt) {//GEN-FIRST:event_graphicsCard3MouseClicked
        toogle(graphicsCard3);

    }//GEN-LAST:event_graphicsCard3MouseClicked

    private void graphicsCard2MouseClicked(MouseEvent evt) {//GEN-FIRST:event_graphicsCard2MouseClicked
        toogle(graphicsCard2);
    }//GEN-LAST:event_graphicsCard2MouseClicked

    private void graphicsCard4MouseClicked(MouseEvent evt) {//GEN-FIRST:event_graphicsCard4MouseClicked
        toogle(graphicsCard4);
    }//GEN-LAST:event_graphicsCard4MouseClicked

    private void graphicsCard1MouseClicked(MouseEvent evt) {
        toogle(graphicsCard1);
    }                                          


    private void focusItem(GraphicsCard graphicsCard){
        int prix = dialog.getPrice(graphicsCard.getItemType());
        graphicsCard.setEnabled(false);
        if (score > prix && size >0) {
            graphicsCard.setBorder(BorderFactory.createLineBorder(Color.BLUE));
            size--;
            System.out.println(score);
            score = score - prix;
            System.out.println(score);
            itemTypesSelect.add(graphicsCard.getItemType());
            focus.put(graphicsCard,!focus.get(graphicsCard));
            updateMarket();
        }
    }

    private void unFocusitem(GraphicsCard graphicsCard){
        graphicsCard.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        size ++;
        score += dialog.getPrice(graphicsCard.getItemType());
        itemTypesSelect.remove(graphicsCard.getItemType());
        focus.put(graphicsCard,!focus.get(graphicsCard));
        updateMarket();
    }




    private void updateMarket() {
        coinScorePanel1.setScore(score);

        // Vérifier chaque carte
        for (Map.Entry<GraphicsCard, Boolean> entry : focus.entrySet()) {
            GraphicsCard card = entry.getKey();
            boolean isFocused = entry.getValue();

            // Si la carte est déjà focus, passer à la suivante
            if (isFocused) {
                continue;
            }

            // Si la carte est désactivée et le score est inférieur au prix de la carte et la taille de l'inventaire est vide, l'activer
            if (!card.isEnabled() && (score < dialog.getPrice(card.getItemType()) && size == 0)) {
                card.setEnabled(true);
            }
            // Sinon, si la carte est activée et le score est supérieur ou égal au prix de la carte et la taille de l'inventaire n'est pas vide, la désactiver
            else if (card.isEnabled() && (score >= dialog.getPrice(card.getItemType()) ||  size > 0)) {
                card.setEnabled(false);
            }
        }
    }

    private void valider() {
        if (!itemTypesSelect.isEmpty()) {
            dialog.buy(player, itemTypesSelect);
            dialog.print(player.toString() + " a acheté :");
            for (Map.Entry<GraphicsCard, Boolean> entry : focus.entrySet()) {
                GraphicsCard card = entry.getKey();
                boolean isFocused = entry.getValue();
                if (isFocused) {
                    dialog.print(card.getItemType() + " pour " + dialog.getPrice(card.getItemType()) + " $");
                }
            }
        } else {
            dialog.print(player.toString() + " n'a rien acheté.");
        }
        dispose();
        System.out.println(itemTypesSelect);
    }


    public void toogle(GraphicsCard graphicsCard) {
        if (focus.get(graphicsCard)) {
            unFocusitem(graphicsCard);
        } else {
            focusItem(graphicsCard);
        }
        System.out.println("\nContenu de la HashMap :");
        for (Map.Entry<GraphicsCard, Boolean> focus : focus.entrySet()) {
            System.out.println(focus.getKey().getItemType() + " : " + focus.getValue());
        }
    }


    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> new Market(new JFrame(),true, Player.JACK_LE_BORGNE, new IDialog() {
            @Override
            public CellType[] getCellsType() {
                CellType[] cellsType = new CellType[30];
                for (int i = 0; i < 30; i++) {
                    cellsType[i] = CellType.NORMAL;
                }
                return cellsType;
            }

            @Override
            public int getPrice(ItemType itemType) {
                return 75;
            }

            @Override
            public int getSizeInventaireAvailable(Player player) {
                return 3;
            }

            @Override
            public int checkfound(Player player) {
                return 43434;
            }

            @Override
            public void endTurn() {
            }

            @Override
            public ItemType[] getItemMarket() {
                ItemType[] itemTypes = new ItemType[4];
                itemTypes[0] = CLOVER;
                itemTypes[1] = BANDANA;
                itemTypes[2] = GUNPOWDER;
                itemTypes[3] = LUCIDITY_STONE;
                return  itemTypes;
            }


            @Override
            public void buy(Player player, List<ItemType> itemTypesSelect) {

            }

            @Override
            public String getNameItem(ItemType itemType) {
                return  itemType.toString();
            }

            public String getDescribe2(ItemType itemType) {
                return null;
            }

            @Override
            public void useItem(int itemIndex, Player player) {

            }

            @Override
            public void throwItem(int itemIndex, Player player) {

            }

            @Override
            public String getDescribe2(int itemIndex) {
                return null;
            }

            @Override
            public void print(String s) {

            }
            
            @Override
            public ItemType[] getDroppedItems(int cellIndex){
                ItemType[] itemTypes = new ItemType[0];
                return itemTypes;
            }
        
            @Override
            public int getNumberOfDroppedItems(int cellIndex){
                return -1;
            }

            public String getDescribe(ItemType itemType) {
                return "Lorem ipsum dolor sit amet, consectetur adipiscing elit,";
            }
        }).setVisible(true));
    }


    private final HashMap<GraphicsCard,Boolean> focus;
    private final Player player;
    private final IDialog dialog;
    private final ItemType[] itemTypes;
    private final List<ItemType> itemTypesSelect;
    private int score ;
    private int size;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.call_of_rum.boundary.presentation.CoinScorePanel coinScorePanel1;
    private fr.call_of_rum.boundary.presentation.GraphicsCard graphicsCard1;
    private fr.call_of_rum.boundary.presentation.GraphicsCard graphicsCard2;
    private fr.call_of_rum.boundary.presentation.GraphicsCard graphicsCard3;
    private fr.call_of_rum.boundary.presentation.GraphicsCard graphicsCard4;
    private fr.call_of_rum.boundary.presentation.InventoryPanel inventoryPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables



}
