/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.call_of_rum;

import org.junit.Test;

import static org.junit.Assert.*;

public class MainTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
